### ISSUE TITLE
指令依赖的数据发生变更了怎么办？

### ISSUE THREAD

**Issue by shenxiang11** [BWrong/auth-tool#1]
请问 getStorage('permissions') 后续如果有变更，不刷新不生效吗？

**Comment by BWrong** [comment]
hasAuth这个方法会在绑定该指令的元素渲染的时候执行，所以你说的数据变化只要是在渲染该元素前的就没问题，你说的这种情况，可以在把getStorage('permissions')换成从vuex去取，这样数据都在vuex维护

**Comment by BWrong** [comment]
`authMap = authMap || getStorage('permissions') || [];`改成`authMap = getStorage('permissions') || [];`这样也可以，每次都从storage去拿，不缓存，有更新操作storage数据更新就行
