### ISSUE TITLE
请问你这个怎么用》

### ISSUE THREAD

**Issue by ZhongHongLi** [BWrong/auth-tool#2]

**Comment by ZhongHongLi** [comment]
> _No description provided._

请问这个用法

**Comment by BWrong** [comment]
1. 首先安装，而且确保你的路由和后端返回的数据格式都和要求的一致。
2. 然后在需要生成数据的地方，调用ganerAuthData方法，依次传入路由、后台返回的权限数据
3. 将会返回清洗后的路由routes，使用addRoutes动态注册；另外还返回来了menus，此数据是用来渲染菜单，和控制页面内元素是否向用户展示（其实就是authDirective指令需要用到的数据）

**Comment by ZhongHongLi** [comment]
谢谢。下次我改这个用一下。后台需要返回components的路劲吗这个应该不用吧


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BWrong/auth-tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 上午10:59
收件人:&nbsp;"BWrong/auth-tool"<auth-tool@noreply.github.com&gt;;
抄送:&nbsp;"遗忘的小丑"<www.fz948605929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BWrong/auth-tool] 请问你这个怎么用》 (#2)





  
首先安装，而且确保你的路由和后端返回的数据格式都和要求的一致。
 
然后在需要生成数据的地方，调用ganerAuthData方法，依次传入路由、后台返回的权限数据
 
将会返回清洗后的路由routes，使用addRoutes动态注册；另外还返回来了menus，此数据是用来渲染菜单，和控制页面内元素是否向用户展示（其实就是authDirective指令需要用到的数据）

**Comment by BWrong** [comment]
不用，只用那个标识对应就行了，components和path这些还是前端管理好一点，不用和后台有太多的耦合。比如前端需要改下path或者component名字，这样我只要保证标识还是对应就行了，而不需要再去后台改path和component

**Comment by ZhongHongLi** [comment]
你那个是根据&nbsp;"permission": "system" 这个后台的根据我们自己写的路由对应起来就好了是吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wrong"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午11:03
收件人: "BWrong/auth-tool"<auth-tool@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BWrong/auth-tool] 请问你这个怎么用》 (#2)





 
不用，只用那个标识对应就行了，components和path这些还是前端管理好一点，不用和后台有太多的耦合。比如前端需要改下path或者component名字，这样我只要保证标识还是对应就行了，而不需要再去后台改path和component

**Comment by BWrong** [comment]
1. 生成数据
![](https://gitee.com/letwrong/Picture/raw/master/20201224110113.png)
2. 注册指令
![image](https://user-images.githubusercontent.com/20485299/103056449-ef4cb900-45d7-11eb-9b09-7038e6a51e49.png)
3. 同理从缓存的menus获取数据，渲染菜单，此处注意一下，就是如果这个menus中如果还包含按钮等，需要在渲染前先自己过滤一下。

**Comment by ZhongHongLi** [comment]
能加个联系方式吗，我看图片加载失败了。也能方便问你。感谢，扣扣都行谢谢！！！！ 948605929




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wrong"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午11:08
收件人: "BWrong/auth-tool"<auth-tool@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BWrong/auth-tool] 请问你这个怎么用》 (#2)





  
生成数据
 
 
注册指令
 
 
同理从缓存的menus获取数据，渲染菜单，此处注意一下，就是如果这个menus中如果还包含按钮等，需要在渲染前先自己过滤一下。

**Comment by BWrong** [comment]
好的，后面我写篇详细的使用说明，再配上demo

**Comment by ZhongHongLi** [comment]
行吧，我关注你掘金了后面直接私聊你也行吧！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wrong"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午11:11
收件人: "BWrong/auth-tool"<auth-tool@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BWrong/auth-tool] 请问你这个怎么用》 (#2)





 
好的，后面我写篇详细的使用说明，再配上demo

**Comment by BWrong** [comment]
ok

**Comment by ZhongHongLi** [comment]
感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wrong"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午11:14
收件人: "BWrong/auth-tool"<auth-tool@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BWrong/auth-tool] 请问你这个怎么用》 (#2)





 
ok
