### ISSUE TITLE
给个demo

### ISSUE THREAD

**Issue by zss1004504439** [BWrong/auth-tool#3]
有实际的例子吗

**Comment by BWrong** [comment]
> 有实际的例子吗

https://github.com/BWrong/admin-antd-vue3

**Comment by BWrong** [comment]
> 有实际的例子吗
![image](https://user-images.githubusercontent.com/20485299/118273573-a9e14780-b4f6-11eb-8ff8-df728f1b0e54.png)
![image](https://user-images.githubusercontent.com/20485299/118273651-c8dfd980-b4f6-11eb-96c2-c32549f2067a.png)

跟着这个函数去查找，拉取项目执行npm run serve:mock查看效果，菜单数据是模拟的，在mock/common/menu.json里面
