### ISSUE TITLE
initAuth方法和文档描述不一致啊。没有过滤掉没有权限的路由

### ISSUE THREAD

**Issue by kele59** [BWrong/auth-tool#4]
`const { routes, menus } = initAuth({ routes, permissions, authKey: 'permission' });`

假设 routes 里定义了 路由A（permission: 'user/hierarchy',），也就是 router/dynamicRoutes/user.ts 中定义了路由A。
 permissions 没有定义 'user/hierarchy'权限

返回的结果 routes 中，还是有  路由A。而且 menus为undefined

"@bwrong/auth-tool": "^3.0.7"

**Comment by BWrong** [comment]
没有定义permissions的路由默认是给了权限的，如果需要修改该行为可以通过option.checkAuth(route, authMap)自己控制过滤策略
